name: KaiU Connection
event: KaiUConnection
code: KaiUConnection
version: 1.0.0
service:
    - ConnectionServiceProvider
orm.path:
    - /Resource/doctrine
const:
    api_url: https://admin.kaiu-marketing.com/api/sites