<?php
namespace Plugin\KaiUConnection\Repository;

use Doctrine\ORM\EntityRepository;
use Plugin\KaiUConnection\Entity\Tag;
use Eccube\Common\Constant;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
	public function save(Tag $tag)
	{
		$em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {
            $tag->setDelFlg(Constant::DISABLED);
            $em->persist($tag);
            $em->flush($tag);

            $em->getConnection()->commit();
        } catch (\Exception $e) {
            $em->getConnection()->rollback();

            return false;
        }

        return true;
	}

    public function delete(Tag $tag)
    {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {
            $tag->setDelFlg(Constant::ENABLED);
            $em->persist($tag);
            $em->flush($tag);

            $em->getConnection()->commit();
        } catch (\Exception $e) {
            $em->getConnection()->rollback();

            return false;
        }

        return true;
    }
}
